### PR TITLE
AcceptInput changes

### LINKED ISSUE #238: Parameters don't work in CEntityInstance.AcceptInput
The function is incorrectly defined with a string for the input parameter when it should be a `variant_t`, see https://github.com/alliedmodders/hl2sdk/blob/cs2/public/variant.h

### PR DESCRIPTION
**Pull request by Yarukon**
(Might need to test on linux cuz i don't have linux enviroment)

Moved AcceptInput to NativeAPI, this change will fix #238
Added CEntitySystem_AddEntityIOEvent

### CODE REVIEW

File: src/scripting/natives/natives_entities.cpp [hunk 1]
```diff
@@ -195,6 +195,8 @@ void UnhookEntityOutput(ScriptContext& script_context)
 
 void AcceptInput(ScriptContext& script_context)
 {
+    if (!CEntityInstance_AcceptInput) return;
```
Comment (roflmuffin) [inline src/scripting/natives/natives_entities.cpp:198]: I think we can hard-fail at this point using `script_context.ThrowNativeError()`

**Review by roflmuffin — APPROVED** [review]
